apiVersion: v1
kind: Secret
metadata:
  name: env-secret
type: Opaque
data:
  POSTGRES_USERNAME: cG9zdGdyZXM=  # Base64-encoded "admin"
  POSTGRES_PASSWORD: cG9zdGdyZXM=  # Base64-encoded "password"
  ACCESS_KEY: QUtJQVlIN0hDSlZSQkI3S1UyVU4=
  SECRET_KEY: TjA4RHFaSUNPNE5KODlDcEhjS01jakFvQ0gySXczNzNRVm1ERkthMQ==
  JWT_SECRET: c2VjcmV0