apiVersion: v1
kind: Secret
metadata:
  name: env-secret
type: Opaque
data:
  POSTGRES_USERNAME: cG9zdGdyZXM=  # Base64-encoded "admin"
  POSTGRES_PASSWORD: cG9zdGdyZXM=  # Base64-encoded "password"
  ACCESS_KEY: QUtJQVVSMkVTUFlGVk9EUjVDTUM=
  SECRET_KEY: dnJKdTJPSGU5V0lQeW9ONWlHK0NRRzlkb3kyQVRrWS9IczAzV2pvOA==
  JWT_SECRET: c2VjcmV0