version: 0.2

env:
  variables:
    DOCKER_USERNAME: "bank22101996"
  parameter-store:
    DOCKER_PASSWORD: "docker_password"

phases:
  pre_build:
    commands:
      - echo are longinning...
      - echo $DOCKER_USERNAME $DOCKER_PASSWORD
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  build:
    commands:
      - echo Build start
      - docker build -t tungts4-reverseproxy ./udagram-reverseproxy
      - docker build -t tungts4-udagram-api-feed ./udagram-api-feed
      - docker build -t tungts4-udagram-api-user ./udagram-api-user
      - docker build  -t tungts4-udagram-frontend  ./udagram-frontend
      - echo build done, start tag
      - docker tag tungts4-reverseproxy 225702921/tungts4-reverseproxy:1.0.1
      - docker tag tungts4-udagram-api-feed 225702921/tungts4-udagram-api-feed:1.0.1
      - docker tag tungts4-udagram-api-user 225702921/tungts4-udagram-api-user:1.0.1
      - docker tag tungts4-udagram-frontend 225702921/tungts4-udagram-frontend:1.0.1
  post_build:
    commands:
      - echo build complete
      - echo Pushing
      - docker push 225702921/tungts4-reverseproxy:1.0.1
      - docker push 225702921/tungts4-udagram-api-feed:1.0.1
      - docker push 225702921/tungts4-udagram-api-user:1.0.1
      - docker push 225702921/tungts4-udagram-frontend:1.0.1